### ISSUE TITLE
How can i request multi  permissions

### ISSUE THREAD

**Issue by cooliean** [lucasferreira/react-native-android-permissions#1]
let pers = ['android.permission.ACCESS_FINE_LOCATION','android.permission.CAMERA']
        requestPermission(pers).then((result) => {
            console.log("Granted!", result);
            // now you can set the listenner to watch the user geo location
        }, (result) => {
            console.log("Not Granted!");
            //this.refs.tvTip.text = ";sfadfaf";
            console.log(result);
        });

is not work

**Comment by lucasferreira** [comment]
Hi @cooliean,

are you shure?

In background the module only works with arrays, if you pass only one perm request I convert to array before pass to the native module:

``` javascript
if(typeof perm == "string") perm = [perm];
```

The module are designed to work with more than one permissions:

``` java
public void requestPermission(**final ReadableArray permsArray**, final int reqCode, final Promise promise)
```

Don't forget to put in _AndroidManifest.xml_ the same permissions that you need to ask in future in run time.

If this keep didn't work, I will send you a zip sample.

**Comment by cooliean** [comment]
@lucasferreira Thank you for your answer , It Word i was  forget to put in AndroidManifest.xml the same permissions that you need to ask in future in run time.

Thanks again.

**Comment by niranjan-b-prajapati** [comment]
@cooliean , @lucasferreira  can you please provide me the code for passing multiple permissions in the checkPermission and requestPermission function, I have already added the permissions in manifest file.

**Comment by lucasferreira** [comment]
Hi @niranjan-b-prajapati 

Just pass an array of permissions:

``` javascript
requestPermission(["android.permission.ACCESS_FINE_LOCATION", "android.permission.CAMERA"]).then((result) => {
        console.log("Granted!", result);
        // now you can set the listenner to watch the user geo location
      }, (result) => {
        console.log("Not Granted!");
        console.log(result);
      });
```

**Comment by niranjan-b-prajapati** [comment]
Thanks @lucasferreira  will try and let you know. 

One more question I have upgraded RN to 0.34.1 from 0.21 will the component work ? as you mentioned that once RN introduces its own Permissions class this will be deprecated, and I guess RN has introduced in RN 0.35.

**Comment by lucasferreira** [comment]
My component still working @niranjan-b-prajapati ;)

**Comment by niranjan-b-prajapati** [comment]
@lucasferreira Sorry for late reply as was out of town on leave for festival. 

I am getting error while checking and requesting for multiple permissions as mentioned in above example.

Following is my code: 

```
onAvatarClick() {
    console.log(' on RegistrationScreen onAvatarClick');      
       checkPermission(["android.permission.CAMERA","android.permission.WRITE_EXTERNAL_STORAGE","android.permission.INTERNET"])
.then((result) => {
    console.log("checkPermission CAMERA Already Granted!", result);
    this.onloadPhoto();
}, (result) => {
     requestPermission(["android.permission.CAMERA","android.permission.WRITE_EXTERNAL_STORAGE","android.permission.INTERNET"])
.then((result) => {
     console.log("requestPermission CAMERA Granted!", result);
     this.onloadPhoto();       
}, (result) => {
    console.log("requestPermission CAMERA  Not Granted!", result);
});
    console.log("checkPermission CAMERA Not Granted!", result);
});
}
```

Following is the screenshot of the same:

![checkpermissions error](https://cloud.githubusercontent.com/assets/22167542/20211567/2437d37a-a825-11e6-90b0-72613466c31a.jpg)

Can you please help me on this?

**Comment by lucasferreira** [comment]
HI @niranjan-b-prajapati 

Sorry for delayed answer, but the _checkPermission_ can check only one permission per time. Array use are only allowed at _requestPermission_ method.

By the way, you could try the native module https://facebook.github.io/react-native/docs/permissionsandroid.html could be useful too.
