### ISSUE TITLE
Doesn't work when running headless js task

### ISSUE THREAD

**Issue by rcidt** [lucasferreira/react-native-android-permissions#11]
When running `checkPermissions` inside a HeadlessJS task, it returns
`{ [Error: Activity doesn't exist] framesToPop: 1, code: 'E_ACTIVITY_DOES_NOT_EXIST' }`

**Comment by rcorrie** [comment]
Hey @lucasferreira there is no need to pass an activity to `ContextCompat.checkSelfPermission`, instead we can pass the reactContext. 

This is fixed in the PR I submitted.

**Comment by lucasferreira** [comment]
Thanks @rcorrie ;) your PR are merged and published.

**Comment by rcorrie** [comment]
thanks @lucasferreira!
