### ISSUE TITLE
Error RNPermissionModule cannot find symbol Context

### ISSUE THREAD

**Issue by butkimtinh** [lucasferreira/react-native-android-permissions#13]
I get error when run react-native run-android.

:react-native-android-permissions:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.). /home/joebiz/Desktop/react_native_app/node_modules/react-native-android-permissions/android/src/main/java/com/burnweb/rnpermissions/RNPermissionsModule.java:44: error: cannot find symbol Context context = getReactApplicationContext(); ^ symbol: class Context location: class RNPermissionsModule 1 error :react-native-android-permissions:compileReleaseJavaWithJavac FAILED

**Comment by lucasferreira** [comment]
Hi @butkimtinh 

What is your React Native version?

**Comment by rcorrie** [comment]
Hey @lucasferreira this issue was introduced by my PR last week. I have submitted a PR to patch this.

https://github.com/lucasferreira/react-native-android-permissions/pull/14

Sorry for the bug

**Comment by lucasferreira** [comment]
Thanks @rcorrie 

@butkimtinh could you update your installation and try again?

**Comment by butkimtinh** [comment]
Thanks all, It's good working.
