### ISSUE TITLE
Null pointer exception since getCurrentActivity() can sometimes returns null

### ISSUE THREAD

**Issue by corymsmith** [lucasferreira/react-native-android-permissions#3]
Saw a few crashes on this line specifically. Wondering if this module should take in a context via the constructor or should be using the ReactContext as the context?

``` java
int hasPermission = ContextCompat.checkSelfPermission(getCurrentActivity(), permsArray.getString(i));
```

**Comment by lucasferreira** [comment]
Hi @corymsmith 

I've followed the instructions from here: https://facebook.github.io/react-native/docs/native-modules-android.html

The method "getCurrentActivity()" is the right way to get the Activity from.

But to avoid this crashes that are you reporting, I implemented a new check system:

``` java
Activity currentActivity = getCurrentActivity();

if (currentActivity == null) {
   promise.reject(E_ACTIVITY_DOES_NOT_EXIST, "Activity doesn't exist");
   return;
}
```

Can you update your npm module installation to the latest version?
