### ISSUE TITLE
Add deprecation warning in README

### ISSUE THREAD

**Issue by felipemsantana** [lucasferreira/react-native-android-permissions#8]
Since RN 0.29 there's an official module (in `NativeModules.AndroidPermissions`) to request permissions in Android Marshmallow, although it is undocumented.

Will be released soon a new documented lib (https://github.com/facebook/react-native/pull/9292).

This module should still be useful to who is using RN <= 0.28 and can't upgrade.

**Comment by lucasferreira** [comment]
Thanks for the warning @fmatoss 

But we will wait for the update in oficial documentation until deprecate this module ;)
